spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4o}
  messages:
    encoding: UTF-8

youtube:
  api:
    key: ${YOUTUBE_API_KEY}